resources:
  repositories:
      - repository: templates
        type: github
        name: brandonmcclure/Az-Devops-Pipeline-Templates
        endpoint: githubServiceConnection
        trigger:
          - main
      - repository: self
trigger:
  - main
  - master
pr:
  - main
  - master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: PrepImage
  displayName: Prep docker image
  jobs:
  - job: PrepImage
    displayName: Prep image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: PowerShell@2
      displayName: 'Run Setup script'
      inputs:
        targetType: 'inline'
        script: |
          Install-Module -Name fc_core -Force -Verbose -Scope CurrentUser;
          Import-Module fc_core;
          Get-Command -Module fc_core;
          build/Setup.ps1
    - task: CopyFiles@2
      inputs:
        SourceFolder: ''
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true
        preserveTimestamp: true
    - task: PublishPipelineArtifact@1
      displayName: publish docker_context artifact
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifact: 'docker_context'
        publishLocation: 'pipeline'
- stage: BuildMultiArchImage
  displayName: Build image 
  dependsOn: PrepImage  
  jobs:
    - job: BuildAndPublishImage
      displayName: Build and publish image
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub'
            command: 'login'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'install-module FC_Docker'
        - task: PowerShell@2
          inputs:
            filePath: 'build/Build.ps1'
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub'
            command: 'logout'
    