CREATE DATABASE [container_test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'container_test', FILENAME = N'/var/opt/mssql/data/container_test.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'container_test_log', FILENAME = N'/var/opt/mssql/data/container_test_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [container_test] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [container_test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [container_test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [container_test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [container_test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [container_test] SET ARITHABORT OFF 
GO
ALTER DATABASE [container_test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [container_test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [container_test] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [container_test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [container_test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [container_test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [container_test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [container_test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [container_test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [container_test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [container_test] SET  DISABLE_BROKER 
GO
ALTER DATABASE [container_test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [container_test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [container_test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [container_test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [container_test] SET  READ_WRITE 
GO
ALTER DATABASE [container_test] SET RECOVERY FULL 
GO
ALTER DATABASE [container_test] SET  MULTI_USER 
GO
ALTER DATABASE [container_test] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [container_test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [container_test] SET DELAYED_DURABILITY = DISABLED 
GO
USE [container_test]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [container_test]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [container_test] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
